on:
  create:
    branches:
      - 'release-please*'

permissions:
  contents: write
  pull-requests: write

name: prebuild-new-release

jobs:
  prebuild-new-release:
    # don't run when a release branch is merged
    if: ${{ !contains(github.ref, 'refs/tags/') }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2.0.2
        with:
          version: '1.7'

      - name: Increment build number and set native versions
        id: build_number
        run: |
          oldBuildNumber=$(jq '.buildNumber' package.json)
          jq '.buildNumber += 1' package.json > package.json.tmp
          mv package.json.tmp package.json
          
          npm ci
          
          npx expo prebuild --no-install

#          newBuildNumber=$(jq '.buildNumber' package.json)
#          sed -i'.bak' -e "s/versionCode $oldBuildNumber/versionCode $newBuildNumber/" android/app/build.gradle && rm android/app/build.gradle.bak
#          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" ios/releaseplease/Info.plist
#
#          version=$(jq '.version' package.json)
#          sed -i'.bak' -e "s/versionName \".*\"/versionName $version/" android/app/build.gradle && rm android/app/build.gradle.bak
#          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $version" ios/releaseplease/Info.plist

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add --all
          git commit -m "chore: increment build number and expo prebuild"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          branch: ${{ github.ref }}

